### ISSUE TITLE
Providing Multiple Tasks

### ISSUE THREAD

**Issue by lenglaender** [heartexlabs/label-studio-frontend#1128]
How can I provide multiple tasks in LSF? So that after submitting one task the user gets the next task.

Providing it as proposed for Labelstudio (https://labelstud.io/guide/tasks.html#Basic-Label-Studio-JSON-format) doesn't work for me:

```javascript
task: [
            {
                "id": 1,
                "data": {
                    "my_text": "Opossums like to be aloft in trees."
                }
            },
            {
                "id": 2,
                "data": {
                    "my_text": "Opossums are opportunistic."
                }
            },
            {
                "id": 3,
                "data": {
                    "my_text": "Opossums like to forage for food."
                }
            }
        ]
```

In Chrome I get this error message:
```
main.js:2 Uncaught (in promise) Error: [mobx-state-tree] No matching type for union ({ id: (number | null?); load: boolean?; auth: ({ enable: boolean?; username: string; password: string; to: string } | null?); data: (string | null?); queue: (string | null?)? } | null?)
    at ut (main.js:2:1527272)
    at t.instantiate (main.js:2:1555492)
    at main.js:2:1549445
    at main.js:2:1551857
    at Array.forEach (<anonymous>)
    at t.forAllProps (main.js:2:1551817)
    at t.initializeChildNodes (main.js:2:1549409)
    at new t (main.js:2:1502560)
    at qe (main.js:2:1525428)
    at t.instantiate (main.js:2:1549260)
```

**Comment by juliosgarbi** [comment]
Hey @lenglaender, I hope everything is well! 

Can you provide the config that you are using? With the config that you are using, I can analyze and understand why it's not working!

Thanks! :)

**Comment by lenglaender** [comment]
I have found another solution to the problem and will close this issue now.
Thanks for your quick reply and the help offered!

**Comment by oktesting** [comment]
> have found another solution to the problem and will close this issue now.
> Thanks for your quick reply and the help offered!

could you share your solution to this problem, thank you 😃

**Comment by lenglaender** [comment]
@oktesting I created a task overview page where the user has a link to each individual task. For my use case, this is even better than having the tasks all directly in the Label Studio Frontend one after the other.

**Comment by oktesting** [comment]
I'm new to the LSF and idk whether my question is relevant. However, I followed [https://labelstud.io/guide/frontend.html](url) to create a demo using react, but it works only with a fixed given `task`. I wasn't able to change the `task` dynamically and passing `task` as an array isn't working at all. I looked at the docs but not finding any useful guide for this problem. 😥
