### ISSUE TITLE
Front-end can't load URL from a given task [...]

### ISSUE THREAD

**Issue by Diegovisk** [heartexlabs/label-studio-frontend#1151]
[...] if the task ID is in another "page" from the GET request.

## Context:

This is the GET request whenever you open a project to label stuff:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/20441537/212907852-a08ff03f-8bbd-420d-af15-b9c3315b357e.png">

As we can see:
- It's page size is 30
- It just loads the first page

Also, I use Label Studio to label projects with a lot of tasks (+500), sometimes I like to save the URL for some problematic/confusing tasks for later review.

I'm also using ver 1.5

## My problem:

Whenever I use the URL for a task that has its ID in a range > 30 (from the first ID in the project), that is, out of the first pagination range, I get a blank screen on the labelling side.

Example of URL: `URL-to-label-studio.com/projects/1/data?task=100` In which the project has tasks from ID 1 - 200. 100 is out of the first page range and will not load the labelling view.

## What I have done so far (with no success so far):
- Searched for another way to get the URL for a given task in labelling view;
- Looked in the changelog for 1.7, 1.6 for something related;
- Tried to look for a way to change `page_size` in the request shown above.

Also, I couldn't find in the code something that was related to the first load of the labelling page, but my suggestion was to make something like:

Get first page of /tasks AS `payload` (just an example), 
Check if ID is in range of `payload[0].id + payload.total`. If it isn't either load all pages from first to that point, or just load that page..

Even though I see that it can be a lot of memory and HTTP requests wasted, (just to get one view), there are more ways to do it as well.

**Comment by makseq** [comment]
Are you talking about this functionality when you copy a navigation link from one window to another? Previously we had a problem there, however I've just checked the latest version and it works well. 

https://user-images.githubusercontent.com/501780/213060292-9134b987-430c-4582-9f34-61907253125d.mp4

**Comment by Diegovisk** [comment]
@makseq thanks a lot, I've upgraded to 1.7 and it indeed worked!
