### ISSUE TITLE
Add Next/Prev Button?

### ISSUE THREAD

**Issue by davidheryanto** [heartexlabs/label-studio-frontend#1266]
This is a user feedback for UI experience improvement.

Having used Label Studio for several months, I realize I often need to go to next or previous tasks. Especially when reviewing annotations. 

With the current UI, I have to click on the specific task on the left sidebar. Although it works well, I realize it can be rather inefficient when working with hundreds of tasks, as there are a lot of mouse movements and scrolling.

Right now, I modify the page HTML and CSS to add a next button. This allows me to easily go to next task faster as opposed to clicking on the list of tasks on the left sidebar.

![image](https://user-images.githubusercontent.com/5300554/226786008-2a5c2acf-6d97-49db-a567-262a34589d05.png)

Maybe just some suggestion, if we can add next/prev button in the UI?

**Comment by makseq** [comment]
Why don't you use shift + up / shift + down? (on old version you have to press Enter after, on the latest - just shift up / down).
