### ISSUE TITLE
How can I add ML backend with label studio frontend?

### ISSUE THREAD

**Issue by juhonkang** [heartexlabs/label-studio-frontend#1286]
Furthermore, I also have seen examples in the example folder. Could you give me the server.py script in that START.md?

**Comment by makseq** [comment]
What START.md are you talking about? 

To use ML backend you need LS backend. Without LS backend you have to implement the whole intermediate backend layer between LSF and ML backend.

**Comment by skewgod** [comment]
Hey! is there a guide on how can I integrate my ML model endpoint into my annotation tool?
