### ISSUE TITLE
Bounding boxes from pre-annotations shifted from their original position randomly on refresh.

### ISSUE THREAD

**Issue by taritro98** [heartexlabs/label-studio-frontend#146]
We have input some pre-annotations to display on the frontend. But the pre-annotations are randomly getting shifted out of their original positions a little bit towards the right on refresh and strangely getting fixed again on refreshing the page. Can we get a solution on how to fix this issue?

**Comment by fromnorthpole** [comment]
Hi, @taritro98 ! Could you provide a bit more context about that issue? E.g. it would be helpful if you can attach:
- the version/environment you use
- screenshots or gifs of the problem
- browser console logs with errors
@hlomzik do you have any ideas what's happening there?

**Comment by taritro98** [comment]
Hi. Thank you. The issue got fixed ( as of now atleast) by changing the browser zoom to 90% and back to 100%. I'll provide the necessary kog info in case I encounter it again.
