### ISSUE TITLE
Convenient time series labeling with only one label

### ISSUE THREAD

**Issue by tsabata-datamole** [heartexlabs/label-studio-frontend#184]
When you are annotating time-series with one label (e.g. anomaly detection) it is very inconvenient to select the label all the time. One can avoid it by selecting the "Keep label selected after creating a region" option but when the region is removed the label is deselected again.

It would be very convenient to have an option to keep one label always on. You do not need to select the label as you have only one possibility and the label is not deselected on delete. It would be also nice if you can set up the default label that is selected when the view is shown for the first time.

**Comment by makseq** [comment]
@tsabata-datamole please, check the latest LS master, now a label is always on even after deleting.
