### ISSUE TITLE
Dialogue colours are hard to distinguish

### ISSUE THREAD

**Issue by tClelford** [heartexlabs/label-studio-frontend#187]
The behaviour of the `<Paragraphs>` tag is to generate a background colour for each speaker based on their name. This is cool, but the colours are a bit too muted and it makes it hard for people to distinguish between speakers at a glance. If you're annotating a conversation where different speakers have different possible annotations, this is quite a hinderance. 

Here's the example from the Labelling Interface Config page:

![image](https://user-images.githubusercontent.com/14278954/115013442-f3635600-9ea8-11eb-97e6-68215dfbb285.png)

Although they're different colours, it's difficult to tell them apart. This is a marked difference from the example in the docs:
![image](https://user-images.githubusercontent.com/14278954/115013578-2279c780-9ea9-11eb-9a65-d6b2f55fb5db.png)

A (very) simple solution to this is to increase the alpha value a little in the colour generator so the different colours are more distinct.

**Comment by tClelford** [comment]
I've created a PR with this simple solution but I'm not sure I'm able to link it https://github.com/heartexlabs/label-studio-frontend/pull/186

**Comment by niklub** [comment]
Thank you! PR is merged
