### ISSUE TITLE
Choice duplicates when using Keypoint and Rectangel together

### ISSUE THREAD

**Issue by yixinc0222** [heartexlabs/label-studio-frontend#195]
Hi all, 

I'm facing an issue that stuck me for days. It will be very appreciated if anyone provide any idea to help this issue!

Issue: Doubles choices result will happen when there are KeyPointLabels with Choices and RectangleLabels in the config file. 
Version: 0.7.3
The example of the config file is as below
```
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true"/>
  <KeyPointLabels name="label" toName="image"
                  strokewidth="2" opacity="1" >
      <Label value="Left Eye State" background="red"/>
      <Label value="Right Eye State" background="blue"/>
  </KeyPointLabels>
  <View visibleWhen="region-selected" whenLabelValue="Left Eye State">
    <Header value="Enter Eye Status:"/>
    <Choices name="leye-status" toName="image"
             perRegion="true">
      <Choice value="Eye Open" alias="1"/>
      <Choice value="Eye Half-Open" alias="2"/>
      <Choice value="Eye Barely-Open" alias="3"/>
      <Choice value="Eye Closed" alias="4"/>
      <Choice value="Occluded" alias="5"/>
    </Choices>
    </View>
  <Header value="FaceDetection:"/>
    <RectangleLabels name="face-boxes" toName="image">
        <Label value="TightBoundingBox" background="green"/>
    </RectangleLabels>
</View>
```
And the Choices are like the image below
![image](https://user-images.githubusercontent.com/83842520/117507528-feefed00-af3b-11eb-9c5d-377bc72c576a.png)
When I delete `perRegion="true"` from Choices tag, it will work. But I need the information generated by `perRegion="true"`.

Thanks in advance for any help!

**Comment by niklub** [comment]
@yixinc0222 thanks for your report! This is supposed to be fixed in version 1.3
