### ISSUE TITLE
consistent coordstype between input annotations and output

### ISSUE THREAD

**Issue by mathmanu** [heartexlabs/label-studio-frontend#269]
Hi, 
I was trying to improve the streamlit component: https://github.com/deneland/streamlit-labelstudio
The main thing that it lacks is the ability to take a previous annotation. I just want to give back the annotations that I got to labelstudio.

I noticed that there is a difference in format between what comes out of this frontend and what needs to be given back in annotations in task configuration. I did this formatting change and am passing in annotations in task. Now I am able to see the previous annotations. However there seems to be a problem.

The coordinates that come out seems to be in pixels (coordstype: 'px'), but it seems the input annotations given in task should be in percentage. Is there a way to make this consistent - either percentage all the time or pixels all the time.

**Comment by niklub** [comment]
Hi, @mathmanu ! Thanks for reporting this. We're closing the issue for now, please feel free to reopen it if it persists. Some additional data would be very helpful to continue investigation!
