### ISSUE TITLE
Release 1.4.0 not found on npm or unpkg

### ISSUE THREAD

**Issue by mareksimunek** [heartexlabs/label-studio-frontend#386]
Hi, I can not found release 1.4.0

https://unpkg.com/label-studio@1.4.0/build/static/css/main.css
https://unpkg.com/label-studio@1.4.0/build/static/js/main.js

returns `Cannot find package label-studio@1.4.0`

Also not found in NPM:
https://www.npmjs.com/package/label-studio

Is it related to `Build & Test failing` button?  

Thanks for help. Worst case scenario I will build the from the source :) (I hope)

**Comment by nicholasrq** [comment]
hey. package has been moved from `label-studio` to `@heartexlabs/label-studio`

**Comment by mareksimunek** [comment]
I see, thank you. 
`https://unpkg.com/@heartexlabs/label-studio@1.4.0/build/static/css/main.css`
works like a charm :)
