### ISSUE TITLE
Unclear: label-studio-frontend vs. label-studio/frontend

### ISSUE THREAD

**Issue by kasuteru** [heartexlabs/label-studio-frontend#467]
_Disclaimer: I am used to coding data science code in Python and relatively new to web frameworks, this question might seem trivial for web developers, forgive me for asking it._

I am a bit confused by the existence of seemingly two front-ends for label-studio: There is this repository, and then there is the frontend subfolder in the backend project: https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend 

To me, it looks like this repository contains more generic frontend elements ( labels, relations, segments...), but the "real" frontend is then written in the label-studio/frontend part? How exactly are those two related? Is the front-end code copied to the label-studio project somehow, or imported at runtime?

**Comment by makseq** [comment]
@kasuteru 

>  How exactly are those two related

https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/dist/dm
Data manager build => https://github.com/heartexlabs/dm2

https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/dist/lsf
Editor => https://github.com/heartexlabs/label-studio-frontend
All labeling tools are here

https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/dist/react-app
React app => https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/src
This app combines DM + editor + other LS page like Projects page, Project settings page, Organization page, etc. 
You can build react-app using `make frontend-build` or `make frontend-watch` (also you can install node modules using `make frontend-install`).  

>  Is the front-end code copied to the label-studio project somehow, or imported at runtime?
Yes. You can build DM or LSF manually and copy built files into correspond folders.
