### ISSUE TITLE
Timeseries instant label instead of period

### ISSUE THREAD

**Issue by dflatow** [heartexlabs/label-studio-frontend#535]
### Describe the solution you'd like

Ability to label a specific timestamp instant instead of marking a period of time. 

### A clear and concise description of any alternative solutions or features you've considered.

Alternatively have used the available features and labelled a very short period starting at the timestamp of interest. In post processing, for the specific label, we discarded the labelling period information and used only the “start time” as the timestamp of interest

### Add any other context or screenshots about the feature request here.

An example of our effort to mark timestamp instant.

![image](https://user-images.githubusercontent.com/5514147/157772656-bb82ee84-d349-47fb-90d0-e9864a7f192e.png)

I'm noticing an "instant" field in the output values, but can't figure out how to configure labeling a instant rather than a period.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5514147/157772963-0621dd14-118d-4ce6-a850-33d6f77c0f61.png">

**Comment by makseq** [comment]
Just select a label and double click on time series.

**Comment by dflatow** [comment]
Wohoo!! Will give that a try :) Thanks!
