### ISSUE TITLE
Module not found: Can't resolve 'label-studio' when importing label-studio frontend

### ISSUE THREAD

**Issue by saintsjd** [heartexlabs/label-studio-frontend#55]
I am following the [frontend reference](https://labelstud.io/guide/frontend_reference.html). I have run `npm install label-studio`. It installed successfully.

I get an error when I `import LabelStudio from "label-studio";` 

The error is `Module not found: Can't resolve 'label-studio'`. Is there another way that I should be importing label studio?

**Comment by lvbirui** [comment]
i have the same question. do you find out how to import the components from label studio?

**Comment by saintsjd** [comment]
No. Not yet.

**Comment by mabounassif** [comment]
The components have not been exported. The index.js is just a standalone app

**Comment by nicholasrq** [comment]
Yup, for now `package.json` is missing the `main` property. We're planning to fix it in upcoming releases.

As a temporary solution you can import js and css directly from `label-studio` like this:

```
import LabelStudio from 'label-studio/build/static/js/main.[HASH].js'
import LabelStudioCSS from 'label-studio/build/static/css/main.[HASH].css'
```

Unfortunately, this solution has a drawback: you'll need to update your import statements as the `HASH` thing is different for every release.

To find the HASH just `ls` into the `node_modules/label-studio/build/static/**`. These hashesare different for js and css.
