### ISSUE TITLE
How to use this project for development from label-studio?

### ISSUE THREAD

**Issue by nabinkhadka** [heartexlabs/label-studio-frontend#65]
Is it possible to use this project as a whole instead of just the minified version in label-studio? So that I can fix issues present in this repo but while using the backend too?

**Comment by zeljkomarinkovic** [comment]
I'm also interested in this

**Comment by makseq** [comment]
Hi, please check this readme sectoin: https://github.com/heartexlabs/label-studio-frontend#development

> Is it possible to use this project as a whole instead of just the minified version in label-studio? So that I can fix issues present in this repo but while using the backend too?

yes, build it and replace the files in the main LS repo. It's here - https://github.com/heartexlabs/label-studio/tree/develop/label_studio/frontend/dist/lsf
