### ISSUE TITLE
Wrong url for imported images when label studio start with --host argument

### ISSUE THREAD

**Issue by aisensiy** [heartexlabs/label-studio-frontend#733]
I am using label-studio with the `--host` parameter like this:

```
$ label-studio --host https://openbayes.com/jobs/abc/proxy/8080
```

Every thing works good until I import some images for ocr task. It seems that the generated urls in frontend have more than one `/` between the prefix and the upload path:

<img width="2529" alt="image" src="https://user-images.githubusercontent.com/661860/177247049-4a1967b6-f75c-41d2-a9bb-b4ebff45ccb3.png">

If I mannully remove the extra `/` in the 

```
/jobs/open-tutorials/jobs/proxy/8080 ---->//<---- data/upload/1/df0703be-AAMU4003561_45R1__011_0741_181125_224515_01_Manual_1.jpg
```

the url can access successfully.

**Comment by aisensiy** [comment]
I think it is not the bug from frontend. It is in the backend:

https://github.com/heartexlabs/label-studio/blob/11164d278b06e9b44767b84946877a414565d893/label_studio/data_import/models.py#L47

**Comment by farioas** [comment]
Fixed by https://github.com/heartexlabs/label-studio/pull/2601

Thanks for the contribution!
