### ISSUE TITLE
Performance issues of HighlightMixin.js adding changing root html style attributes

### ISSUE THREAD

**Issue by Stinosko** [heartexlabs/label-studio-frontend#782]
Hey,

I noticed some UI performance issues of the latest release of visual studio frontend (1.4.0) while annotating large text files. Think more than 50 lines of txt in one annotation task.

With some debugging i noticed the issue originate from /src/mixins/HighlightMixin.js, it adds and change global html style attributes. By doing so the browser need to re calculate all styles of all elements in the entire HTML page. This makes the browser less responsive when lots of elements are present, for example big text files with many annotation labels.

The issue originate from using `document.documentElement.style.setProperty(...);` in the `createSpanStylesheet` method.

Original code: 
>  const rules = {
>    [className]: `background-color: var(${variables.color});`,
>    [classNames.active]: `${variables.color}: ${initialActiveColor}`
> }

>  const setColor = color => {
>    style.backgroundColor = newActiveColor;
>    style.color = Utils.Colors.contrastColor(newActiveColor);
>  };

My workaround:  
Comment out all three `document.documentElement.style.setProperty(...);`
>  const rules = {
>    ...
>    [className]: `background-color: ${color};`,
>    [classNames.active]: `background-color: ${initialActiveColor}`
>    ...
> }

>  const setColor = color => {
>    ...
>    stylesheet.rules[0].style.backgroundColor = color;
>    stylesheet.rules[0].style.color = Utils.Colors.contrastColor(color);
>    stylesheet.rules[2].style.backgroundColor = newActiveColor;
>    stylesheet.rules[2].style.color = Utils.Colors.contrastColor(newActiveColor);
>    ...
>  };

**Comment by Stinosko** [comment]
Update: the performance issue is not present in the master branch anymore in this repository!

Not sure how but my workaround is not needed anymore when using the latest version of the master branch of label-studio-frontend with latest release of label-studio 1.5 😄

**Comment by makseq** [comment]
Thank you for your answer ;) Looks like this issue is solved.
