### ISSUE TITLE
In case of Text classification, Reset Button does not uncheck choice

### ISSUE THREAD

**Issue by lalitlsg** [heartexlabs/label-studio-frontend#830]
After clicking on Reset Button, it does not uncheck choice.

<img width="627" alt="Screenshot 2022-09-04 at 5 22 07 PM" src="https://user-images.githubusercontent.com/45810890/188312118-4c7d4cc9-00bf-4f72-b219-53492fb98413.png">

**Comment by makseq** [comment]
@lalitlsg Hi, it's extremely old LSF version, this has been fixed long time ago..
