### ISSUE TITLE
Eraser tool is not working

### ISSUE THREAD

**Issue by jeremyben** [heartexlabs/label-studio-frontend#922]
Hi, We're benchmarking labelling tools, and Labelstudio seems really promising, great job.
Only there's a critical bug in our experience: The impossibility to erase and thus to refine segmentation with brush labels.

The eraser tool is simply not working in the latest production release available: 1.6.0

![image](https://user-images.githubusercontent.com/8047987/197418023-3b329bf1-5412-4412-b95f-0821cf759fb7.png)

Anyone knows a previous version where it worked ?

**Comment by jeremyben** [comment]
Ok I managed to pinpoint the faulty commit: 6cdfe354
I started the app with the previous commit e516329c, and the eraser tool worked as expected.

**Comment by jeremyben** [comment]
Linking to main repo issue: https://github.com/heartexlabs/label-studio/issues/867

**Comment by makseq** [comment]
@jeremyben Thank you for your great exploration, I've created a ticket, hope our frontend team will fix it soon.

**Comment by omaralvarez** [comment]
Same problem here, I hope it gets fixed soon. :)

**Comment by makseq** [comment]
@omaralvarez Have you already tried the latest develop branch from the main LS repo?

**Comment by omaralvarez** [comment]
No, I have not, glad to hear it. Thanks!
