### ISSUE TITLE
1.4.0 not available on CDN 

### ISSUE THREAD

**Issue by lazaroshi** [heartexlabs/label-studio-frontend#944]
The unpkg link in the readme is not available
[https://unpkg.com/label-studio@latest](https://unpkg.com/label-studio@latest) directs to v. 1.0.1 with 1.4.0 not being available at all

It would be nice if this package was updated to publish to unpkg with every new release and if 1.4.0 was available on unpkg
Thanks

**Comment by nicholasrq** [comment]
hello @lazaroshi 

the proper link for >=1.4 is https://unpkg.com/@heartexlabs/label-studio@latest

**Comment by huckw** [comment]
I tried putting this in my html...
```
<link href="https://unpkg.com/heartexlabs@label-studio@latest/build/static/css/main.css" rel="stylesheet">
<script src="https://unpkg.com/heartexlabs@label-studio@latest/build/static/js/main.js"></script>
```
but I get these errors...
```
GET https://unpkg.com/heartexlabs@label-studio@latest/build/static/js/main.js net::ERR_ABORTED 404
GET https://unpkg.com/heartexlabs@label-studio@latest/build/static/css/main.css net::ERR_ABORTED 404
```
How can I use version 1.4.0 (or some modern version which includes `taxonomy`?
